name: DynamicMOTD
main: name.richardson.james.dynamicmotd.DynamicMOTD
version: 1.0.0
author: James Richardson (grandwazir)
description: Dynamic MOTD for the Minecraft server browser
website: https://github.com/grandwazir/DynamicMOTD