name: DynamicMOTD
description: Dynamic MOTD for the Minecraft server browser
author: James Richardson (grandwazir)
website: https://github.com/grandwazir/DynamicMOTD
main: name.richardson.james.bukkit.dynamicmotd.DynamicMOTD
version: ${project.version}
